### PR TITLE
fix: Don't skip first result

### PR DESCRIPTION
**Pull request by michelleshu**

### CODE REVIEW

**Comment by bsouthga** [comment]
Looks good! nice catch 👍

**Comment by yangchristian** [comment]
Looks good to me!

**Comment by michelleshu** [comment]
Will I need to increment the package version for this change to be applied to crosslead-platform?

**Comment by yangchristian** [comment]
Correct. Currently we're just using the commit hash. Don't think we're ready yet to publish to npm.

**Pull request merged**
